# listener TLS
listener 8883
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate false

# data persistence
allow_anonymous false
password_file /mosquitto/config/passwords.txt

# authentication
persistence true
persistence_location /mosquitto/data/

# log
log_type all