services:
  api:
    restart: always
    image: ${API_IMAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iot-api.rule=Host(`${APP_HOST:-jbhuet.fr}`) && PathPrefix(`/api/iot`)"
    environment:
      - APP_ENV
      - APP_SCHEME
      - APP_HOST
      - APP_PORT
      - OAUTH_CLIENT_ID
      - OAUTH_CLIENT_SECRET
      - IOT_API_USERNAME
      - IOT_API_PASSWORD
    networks:
      - reverse_proxy
    depends_on:
      mqtt:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./certs:/certs:ro
    healthcheck:
      # On utilise python car l'image python:3.12-slim n'inclut pas forcément curl ou wget par défaut.
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:80/api/iot/docs')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mqtt:
    restart: always
    image: eclipse-mosquitto:2.0
    environment:
      - IOT_API_USERNAME
      - IOT_API_PASSWORD
      - DEVICE_1_USERNAME
      - DEVICE_1_PASSWORD
      - DEVICE_2_USERNAME
      - DEVICE_2_PASSWORD
      - DEVICE_3_USERNAME
      - DEVICE_3_PASSWORD
      - DEVICE_4_USERNAME
      - DEVICE_4_PASSWORD
      - DEVICE_5_USERNAME
      - DEVICE_5_PASSWORD
    ports:
      - "8883:8883" # MQTT TLS
    volumes:
      - ./config/mqtt/entrypoint.sh:/entrypoint.sh
      - ./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs/mqtt:/mosquitto/certs
      - mqtt_data:/mosquitto/data
    entrypoint: ["/entrypoint.sh"]
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
    networks:
      - reverse_proxy
    healthcheck:
      # Teste la connexion TLS sur le port 8883 en utilisant les credentials de l'API injectés.
      test: ["CMD-SHELL", "mosquitto_pub -h 127.0.0.1 -p 8883 --cafile /mosquitto/certs/ca.crt --insecure -u ${DEVICE_5_USERNAME} -P ${DEVICE_5_PASSWORD} -t 'healthcheck' -m 'ping' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
    image: redis:7-alpine
    restart: always
    networks:
      # Only internal network access
      - reverse_proxy
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  reverse_proxy:
    name: reverse_proxy
    external: true

volumes:
  mqtt_data:
  redis_data:
