name: Reusable Deploy

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      registry:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for config files
        uses: actions/checkout@v5

      - name: Copy config to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "config/"
          target: "/home/${{ secrets.SERVER_USER }}/projects/iot"

      - name: Remote SSH Deployment
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            PROJECT_DIR="/home/${{ secrets.SERVER_USER }}/projects/iot"
            CERTS_DIR="$PROJECT_DIR/certs"
            API_CERTS_DIR="$CERTS_DIR/api"
            MQTT_CERTS_DIR="$CERTS_DIR/mqtt"

            # Generate not found MQTT certs
            mkdir -p "$MQTT_CERTS_DIR"
            if [ ! -f "$MQTT_CERTS_DIR/server.crt" ]; then
              openssl req -new -x509 -days 3650 -nodes -out "$MQTT_CERTS_DIR/ca.crt" -keyout "$MQTT_CERTS_DIR/ca.key" -subj "/CN=IoT_Root_CA"
              openssl genrsa -out "$MQTT_CERTS_DIR/server.key" 2048
              openssl req -new -key "$MQTT_CERTS_DIR/server.key" -out "$MQTT_CERTS_DIR/server.csr" -subj "/CN=${{ secrets.APP_HOST }}"
              openssl x509 -req -in "$MQTT_CERTS_DIR/server.csr" -CA "$MQTT_CERTS_DIR/ca.crt" -CAkey "$MQTT_CERTS_DIR/ca.key" -CAcreateserial -out "$MQTT_CERTS_DIR/server.crt" -days 3650
              chmod 644 "$MQTT_CERTS_DIR/ca.crt" "$MQTT_CERTS_DIR/server.crt" "$MQTT_CERTS_DIR/server.key"
            fi

            # Generate not found JWT API certs
            mkdir -p "$API_CERTS_DIR"
            if [ ! -f "$API_CERTS_DIR/private.pem" ] || [ ! -f "$API_CERTS_DIR/public.pem" ]; then
              openssl genrsa -out "$API_CERTS_DIR/private.pem" 2048
              openssl rsa -in "$API_CERTS_DIR/private.pem" -pubout -out "$API_CERTS_DIR/public.pem"
            fi

            export API_IMAGE="${{ inputs.registry }}/${{ inputs.image_name }}:${{ github.sha }}"
            export APP_ENV="${{ vars.APP_ENV }}"
            export APP_HOST="${{ vars.APP_HOST }}"
            export APP_PORT="${{ vars.APP_PORT }}"
            export OAUTH_CLIENT_ID="${{ vars.OAUTH_CLIENT_ID }}"
            export OAUTH_CLIENT_SECRET="${{ secrets.OAUTH_CLIENT_SECRET }}"
            export IOT_API_USERNAME="${{ vars.IOT_API_USERNAME }}"
            export IOT_API_PASSWORD="${{ secrets.IOT_API_PASSWORD }}"
            export DEVICE_1_USERNAME="${{ vars.DEVICE_1_USERNAME }}"
            export DEVICE_1_PASSWORD="${{ secrets.DEVICE_1_PASSWORD }}"
            export DEVICE_2_USERNAME="${{ vars.DEVICE_2_USERNAME }}"
            export DEVICE_2_PASSWORD="${{ secrets.DEVICE_2_PASSWORD }}"
            export DEVICE_3_USERNAME="${{ vars.DEVICE_3_USERNAME }}"
            export DEVICE_3_PASSWORD="${{ secrets.DEVICE_3_PASSWORD }}"
            export DEVICE_4_USERNAME="${{ vars.DEVICE_4_USERNAME }}"
            export DEVICE_4_PASSWORD="${{ secrets.DEVICE_4_PASSWORD }}"
            export DEVICE_5_USERNAME="${{ vars.DEVICE_5_USERNAME }}"
            export DEVICE_5_PASSWORD="${{ secrets.DEVICE_5_PASSWORD }}"

            cd "$PROJECT_DIR"
            # Secure login to Github Docker registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ inputs.registry }} -u ${{ github.actor }} --password-stdin

            # Generate docker compose file
            docker compose -p "prod" --project-directory . -f ./config/docker-compose.yml config > docker-compose.yml

            # Clean configs files
            find ./config -mindepth 1 -maxdepth 1 ! -name 'mqtt' -exec rm -rf {} +

            # Pull Docker image et restart
            docker compose -f ./docker-compose.yml up --force-recreate --remove-orphans -d --wait --wait-timeout 60

            echo "Deploy finished at $(date '+%Y-%m-%d %H:%M:%S')"
