name: Global IoT API Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # Call build and scan workflow
  ci:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build.yml
    with:
      image_name: aureprod/iot-api
      registry: ghcr.io
    secrets: inherit # Transmet secret (GITHUB_TOKEN, etc.)

  # Call deploy workflow (only if build success)
  cd:
    needs: ci
    uses: ./.github/workflows/deploy.yml
    with:
      image_name: aureprod/iot-api
      registry: ghcr.io
    secrets: inherit
